name: Build and publish latest
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [14-alpine, 16-alpine]
        folder: [azure]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup QEmu so we can build multiplatform
        uses: docker/setup-qemu-action@v1
      - name: Login to docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v1
      - name: Docker meta configuration
        uses: docker/metadata-action@v3
        id: meta
        with:
          images: |
            unleashorg/unleash-community
          tags: type=edge,suffix=-${{ matrix.version }}-${{ matrix.platform }}
      - name: Build tag and push image to Docker hub
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          build-args:
            - NODE_VERSION=${{ matrix.version }}
            - SOURCE_FOLDER=${{ matrix.folder }}
